name: camera_calibration
channels:
- conda-forge
- pkgs/main
dependencies:
- black
- dacite
- icecream
- ipdb
- ipython
- ipywidgets
- isort
# - jaxopt
- jupyterlab-git
- jupyterlab-katex
- jupyterlab-lsp
- jupyterlab_code_formatter
# - numba
- numpy
- opencv
- optax
- pandas
- pillow
- plotly
- pybind11
- python-lsp-server
- ruff
- scikit-learn
- scipy
- tqdm
- pip:
  - calibration/feature_detector/libcbdetect
