name: camera_calibration
channels:
- conda-forge
dependencies:
- black
- build
- cxx-compiler
- icecream
- ipdb
- ipython
- ipywidgets
- isort
- jupyterlab-git
- jupyterlab-katex
- jupyterlab-lsp
- jupyterlab_code_formatter
- numpy
- opencv
- pandas
- pillow
- pkg-config
- plotly
- pybind11
- pytest
- python-lsp-server
- ruff
- scipy
- tqdm
- pip:
  - calibration/features/libcbdetect
