on:
  pull_request:
    paths:
      - "**/*.tex"

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
      - uses: actions/checkout@v3
      - name: Make a Copy of the Original PDF
        run: cp paper/paper.pdf original_copy.pdf
      - name: Make a Copy of the Original PDF
        run: cp paper/presentation.pdf original_copy.pdf
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: "paper/paper.tex"
          push: "no"
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: "paper/presentation.tex"
          push: "no"
      - name: Compare paper/paper.pdf with paper/paper_copy.pdf
        run: |
          if ! cmp --silent paper/paper.pdf paper/paper_copy.pdf; then
            echo "paper/paper.pdf and paper/paper_copy.pdf differ!"
            exit 1
          fi
      - name: Compare paper/presentation.pdf with paper/presentation_copy.pdf
        run: |
          if ! cmp --silent paper/presentation.pdf paper/presentation_copy.pdf; then
            echo "paper/presentation.pdf and paper/presentation_copy.pdf differ!"
            exit 1
          fi
