name: Build pdfs

on:
  pull_request:
    # paths:
    #   - "**/*.tex"

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
      - uses: actions/checkout@v3
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: 'latest'
      - run: cp paper/paper.pdf original_copy.pdf
      - run: cp paper/presentation.pdf original_copy.pdf
      - run: tectonic paper/paper.tex
      - run: tectonic paper/presentation.tex
      - name: Compare paper/paper.pdf with paper/paper_copy.pdf
        run: |
          if ! cmp --silent paper/paper.pdf paper/paper_copy.pdf; then
            echo "paper/paper.pdf and paper/paper_copy.pdf differ!"
            exit 1
          fi
      - name: Compare paper/presentation.pdf with paper/presentation_copy.pdf
        run: |
          if ! cmp --silent paper/presentation.pdf paper/presentation_copy.pdf; then
            echo "paper/presentation.pdf and paper/presentation_copy.pdf differ!"
            exit 1
          fi
