name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: camera_calibration
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py311 .
      - name: Test with pytest
        run: |
          pytest
