name: Build, lint and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-file: environment.yml
          init-shell: >-
            bash
            # powershell
          cache-environment: true
          post-cleanup: "all"

      - name: Cache data directory
        uses: actions/cache@v3
        with:
          path: ./data
          key: dataset-${{ hashFiles('calibration/data/babelcalib/download.py') }}

      - name: Download Babelcalib
        run: python calibration/data/babelcalib/download.py

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py311 .
      - name: Test with unittest
        run: python -m unittest
