name: Build, lint and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('environment.yml') }}
        id: cache

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: environment.yml
          activate-environment: camera_calibration
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Cache data directory
        uses: actions/cache@v3
        with:
          path: ./data
          key: dataset-${{ hashFiles('calibration/data/babelcalib/download.py') }}
      - name: Download Babelcalib
        run: python calibration/data/babelcalib/download.py

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py311 .
      - name: Test with unittest
        run: |
          python -m unittest
